### PR TITLE
Add build directory option.

### PR DESCRIPTION
**Pull request by everythingfunctional**
Added an option to include the name of the build directory, which is just prepended to all of the file names. Also put a comment at the top of the output file that indicates it is an automatically generated file.

### CODE REVIEW

**Comment by ZedThree** [comment]
Hi @bprichar, this looks great, thanks! Do you think you could use `os.path.join` to append `build` ([here](https://github.com/bprichar/fort_depend.py/blob/master/fort_depend.py#L44) and [here](https://github.com/bprichar/fort_depend.py/blob/master/fort_depend.py#L47))? This ensures the correct path separators are included, in case the user forgets them on the command line.

**Comment by everythingfunctional** [comment]
Absolutely. Didn't remember that function at the time. Much safer option, thanks.

**Comment by ZedThree** [comment]
I think fort_depend.py:177 should be

``` python
build = args.build[0] if args.build else ''
```

rather than

``` python
build = args.build[0] if args.build else None
```

otherwise I get an error from `os.path.join`.

**Comment by everythingfunctional** [comment]
Ok, I'll fix that right quick.

**Pull request merged**
